apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-web-log-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-pod-log-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-web-read-logs
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-web-log-reader
roleRef:
  kind: Role
  name: {{ .Release.Name }}-pod-log-reader
  apiGroup: rbac.authorization.k8s.io